version: '3'

services:
  php1:
    container_name: php1
    image: wachira90/php:7.4
#    image: wachira90/php:7.2
#    image: wachira90/php:7.3
#    image: wachira90/php:7.1    
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    expose:
      - 9000

  nginx1:
    container_name: nginx1
    image: wachira90/nginx:1.21.4
#    image: wachira90/nginx:1.18.0
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
      - ./conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    healthcheck:
      interval: 5s
    ports:
      - "7000:80"
      - "4443:443"

networks:
  default:
